### PR TITLE
Fix/sale price currencies

### LINKED ISSUE #213: Price should be a number rather than a dropdown
Price should be an integer and we can add another field for `price_currency`. This will be many-to-one, defaulting to USD.

- use the current field as price_currency?

### PR DESCRIPTION
**Pull request by scottrepreneur**
Relies on the config update in #218 , so could just use this one instead. In addition to that one:

- add `sale_price` & `sale_currency` to the `product` model
- migrate `products` with `price_currencies` to the new fields

Fixes #213 

To test these custom migrations

- comment out the copy in Dockerfile 
  `# && cp -r /directus/custom_migrations/* /directus/extensions/migrations \`
- `docker compose --profile cms up`
- `docker ps` // get the ID for the directus container for `CONTAINER` below
- `cd packages/cms/custom_migrations`
- `docker cp . CONTAINER:/directus/extensions/migrations`
- *Make some changes to the data (add a price_currency & product)*
- `docker exec CONTAINER npx directus database migrate:latest`

### CODE REVIEW

File: packages/cms/custom_migrations/20220825A-migrate-price-currencies.js [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+  async up(knex) {
+    // add default USD, ETH for currencies
+    await knex('currencies').insert({ currency: 'USD' });
+    await knex('currencies').insert({ currency: 'ETH' });
+
+    const priceCurrencies = await knex('price_currencies');
+    const products = await knex('products').whereNotNull('price');
+    const currencies = await knex('currencies');
+
+    const getThingByKey = (things, key, value) => {
```
Comment (META-DREAMER) [inline packages/cms/custom_migrations/20220825A-migrate-price-currencies.js:13]: Could also use Lodash keyBy: https://lodash.com/docs/#keyBy

File: packages/cms/custom_migrations/20220825A-migrate-price-currencies.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+      return null;
+    };
+
+    for (let i = 0; i < products.length; i++) {
+      const product = products[i];
+      // get price currency for product
+      const priceCurrency = getThingByKey(
+        priceCurrencies,
+        'id',
+        product?.price,
```
Comment (META-DREAMER) [inline packages/cms/custom_migrations/20220825A-migrate-price-currencies.js:28]: Instead of optional operator here, should just check if product is nullish above and skip that iteration of the loop (e.g. `if (!product) continue;`)

File: packages/cms/custom_migrations/20220825A-migrate-price-currencies.js [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+      if (sale_price && sale_currency) {
+        await knex('products')
+          .where({ id: product?.id })
+          .update({ sale_price, sale_currency: sale_currency?.id });
+      }
+    }
+  },
+
+  async down() {
+    // do something?
```
Comment (META-DREAMER) [inline packages/cms/custom_migrations/20220825A-migrate-price-currencies.js:46]: Would basically be the reverse of this to rollback any changes made in case migration fails. Not critical for this one IMO.

**Review by META-DREAMER — APPROVED** [review]
Some minor suggestions, feel free to merge after addressing

File: packages/cms/custom_migrations/20220825A-migrate-price-currencies.js (hunk 1 above)
Comment (scottrepreneur) [reply packages/cms/custom_migrations/20220825A-migrate-price-currencies.js:13]: is lodash available inside the directus env?

Comment (scottrepreneur) [reply packages/cms/custom_migrations/20220825A-migrate-price-currencies.js:13]: ah sick
